### ISSUE TITLE
Dell FW repo update

### ISSUE THREAD

**Issue by digi-talo** [dell/iDRAC-Redfish-Scripting#100]
I'm trying to automate FW upgrades. 
`dell_fw_repo_update.py` seems most adequate for my environment.
I extracted the `repository` directory from the `PER640_BOOTABLE_20.03.00.124.iso` to an http server in a directory named dell. `HTTP` is listed as a supported network share but it fails to download the `Calalog.xml` (the file is there and accessible)

I ran `InstallFromRepositoryREDFISH.py -ip 10.160.20.100 -u root -p password -i y --ipaddress 10.160.5.5:81 --sharename dell --applyupdate False --sharetype HTTP` 
I tried as well placing the files in the root directory of the webserver and ran `InstallFromRepositoryREDFISH.py -ip 10.160.20.100 -u root -p password -i y --ipaddress 10.160.5.5:81 --applyupdate False --sharetype HTTP` but both attempts failed.

The description in the script is not very clear on http shares, could you please clarify how to use them?

**Comment by texroemer** [comment]
Hi @digi-talo 

For iDRAC repository update support, you must either use Dell downloads repository or create a custom repository created using Dell Repository Manager (DRM) utility. 

For your HTTP share, did you use Apache or IIS? 

Did you try using Dell HTTP downloads repository (143.166.147.76) to validate this share works? This would be the recommended share to use which is always updated with latest firmware versions for all devices iDRAC supports for updates. Example below shows using this repository. 

C:\Python38-32>InstallFromRepositoryREDFISH.py -ip 100.65.84.79 -u root -p calvin -i y --ipaddress 143.166.147.76 --sharetype HTTP --applyupdate False --rebootneeded False

- WARNING, arguments and values for InstallFromRepository method

ApplyUpdate: False
RebootNeeded: False
IPAddress: 143.166.147.76
ShareType: HTTP

- PASS: POST command passed for method "InstallFromRepository", status code 202 returned
- PASS, repository job ID JID_844464463399 successfully created
- WARNING, job ID JID_844464463399 not marked completed, current job information:

* Name: Repository Update
* Job Status: Downloading the Catalog.xml update package.
* Current job execution time: 0:00:00


- PASS, job ID JID_844464463399 successfully marked completed

- Final detailed job results -

@odata.context: /redfish/v1/$metadata#DellJob.DellJob
@odata.id: /redfish/v1/Managers/iDRAC.Embedded.1/Jobs/JID_844464463399
@odata.type: #DellJob.v1_0_1.DellJob
CompletionTime: 2020-03-17T07:01:02
Description: Job Instance
EndTime: None
Id: JID_844464463399
JobState: Completed
JobType: RepositoryUpdate
Message: Job completed successfully.
MessageArgs: ['NA']
MessageId: RED001
Name: Repository Update
PercentComplete: 100
StartTime: TIME_NOW
TargetSettingsURI: None



- WARNING, "ApplyUpdate = False" selected, execute script with -r agrument to view the repo update list which will report devices detected for firmware updates

**Comment by digi-talo** [comment]
We do not allow internet access from our OOB network so that's unfortunately not an option.
I created an update package via the Dell Repository Manager (DRM) utility and placed that on our web sever (which is nginx). After switching to port 80 it can now download the Catalog.xml but it fails with `FAIL: Job ID JID_845630416486 failed, detailed error message is: Unable to complete the firmware update operation because the specified firmware image is for a component that is not in the target system inventory`

**Comment by texroemer** [comment]
Failure means you have a firmware DUP in your custom repository which is not supported for the server model you are executing the script on. 

- Did you download the correct DUP for the hardware in your server from Dell Support Site?
- If you have the correct DUP for HW in your server platform, when you created the repository using DRM, did you select the correct platform model? You can view the Catalog.xml which should report supported platforms.

Thanks

**Comment by digi-talo** [comment]
Not sure what you mean. The server in question is a PowerEdge R640.
 I tried two approaches, as before I extracted the `repository`  directory from `PER640_BOOTABLE_20.03.00.124.iso` which contains a Catalog.xml and all the binaries. That failed with above error message.
Then I tried as suggested with Dell Repository Manager (DRM) utility:
I added a repository and selected under manual:
- Systems --> R640
- Operating Systems --> All operating systems in base catalog
- Components --> BIOS & Firmware
Then I selected PowerEdge R640 (Linux) and chose "export" where I chose Share and selected a directory. The content of that directory (which contains a Catalog.xml and folders with binaries) I uploaded to our webserver. The script failed again with the same error.(`Unable to complete the firmware update operation because the specified firmware image is for a component....`)

**Comment by texroemer** [comment]
The issue is you selected Linux, Catalog updates with iDRAC only supports Windows DUPs. 

Here are the steps to create a custom repository using DRM:

1. Repository home page, Select "Add Repository"
2. In the Add Repository box, fill in Repository Name, Description (optional) and for Base Catalog, select "None". Repository Type should be set to Manual. Select "Add".
3. Back on Repository home page, select check box for the repository you just created. Now select "Add Bundles".
4. Select "Add Empty Bundle" which will display "Add Bundles" window
5. Pass in unique Bundle Name, select "Windows-64" for DUP format, select your Server Model and select "Add".
6. Back on home page, you should now see an empty bundle created. Select the Bundle and now click on "Import".
7. Browse to Windows DUP location and select the Window DUP you want to add to your bundle. Now select "Import" which will take you back to the home page. Expand your bundle which you should now see the DUP you just added.
8. Repeat steps 6 and 7 if you need to add more DUPs. If not you can continue to step 9.
9. Select Export from the home page, then select "Export Catalog Only" option. Browse for the location where you have the Windows DUP(s) and save the Catalog here. Select Export button.
10. Go to the directory where the Catalog is saved and rename the Catalog to "Catalog.xml".
11. Creating custom repository is complete. Copy your repository to your HTTP server which should contain the DUP(s) and Catalog file.


Example of the repo i created using DRM for R640 which contains BIOS update. I copied the repo to my Apache server.

[root@linux R640_update_repo]# ls -la
total 28184
drwxrwxrwx  2 root   root       4096 Mar 18 10:52 .
drwxrwxrwx 23 apache apache    20480 Mar 18 10:48 ..
-rwxr--r--  1 root   root   28787480 Mar 18 09:48 BIOS_004Y7_WN64_2.5.4.EXE
-rwxr--r--  1 root   root      11222 Mar 18 10:03 Catalog.xml

Example of running the repo update script using this custom repo.


C:\Python38-32>InstallFromRepositoryREDFISH.py -ip 100.65.84.79 -u root -p calvin -i y --ipaddress 100.65.84.150 --sharetype HTTP --sharename updates_http/R640_update_repo --applyupdate True --rebootneeded True

- WARNING, arguments and values for InstallFromRepository method

ApplyUpdate: True
RebootNeeded: True
IPAddress: 100.65.84.150
ShareType: HTTP
ShareName: updates_http/R640_update_repo

- PASS: POST command passed for method "InstallFromRepository", status code 202 returned
- PASS, repository job ID JID_845335149313 successfully created

- WARNING, repository package successfully downloaded. If version changed detected for any device, update job ID will get created and execute for that device

- WARNING, job ID JID_845335149313 not marked completed, current job information:

* Name: Repository Update
* Job Status: Package successfully downloaded.
* Current job execution time: 0:00:06


- PASS, job ID JID_845335149313 successfully marked completed

- Final detailed job results -

@odata.context: /redfish/v1/$metadata#DellJob.DellJob
@odata.id: /redfish/v1/Managers/iDRAC.Embedded.1/Jobs/JID_845335149313
@odata.type: #DellJob.v1_0_1.DellJob
CompletionTime: 2020-03-18T07:12:16
Description: Job Instance
EndTime: None
Id: JID_845335149313
JobState: Completed
JobType: RepositoryUpdate
Message: Job completed successfully.
MessageArgs: ['NA']
MessageId: RED001
Name: Repository Update
PercentComplete: 100
StartTime: TIME_NOW
TargetSettingsURI: None



- WARNING, repository update job marked completed. Script will now check to see if any update job(s) were created due to different firmware version change detected

- WARNING, scheduled update job ID detected, server rebooting to apply the update(s)
- WARNING, job ID JID_845335194463 not marked completed, current job information:

* Name: update:DCIM:INSTALLED#741__BIOS.Setup.1-1
* Job Status: Task successfully scheduled.
* Current job execution time: 0:00:00

- WARNING, job ID JID_845335194463 not marked completed, current job information:

* Name: update:DCIM:INSTALLED#741__BIOS.Setup.1-1
* Job Status: Task successfully scheduled.
* Current job execution time: 0:00:16

- WARNING, job ID JID_845335194463 not marked completed, current job information:

* Name: update:DCIM:INSTALLED#741__BIOS.Setup.1-1
* Job Status: Task successfully scheduled.
* Current job execution time: 0:00:31

- WARNING, job ID JID_845335194463 not marked completed, current job information:

* Name: update:DCIM:INSTALLED#741__BIOS.Setup.1-1
* Job Status: Task successfully scheduled.
* Current job execution time: 0:00:47

- WARNING, job ID JID_845335194463 not marked completed, current job information:

* Name: update:DCIM:INSTALLED#741__BIOS.Setup.1-1
* Job Status: Task successfully scheduled.
* Current job execution time: 0:01:03

- WARNING, job ID JID_845335194463 not marked completed, current job information:

* Name: update:DCIM:INSTALLED#741__BIOS.Setup.1-1
* Job Status: The specified job is in progress.
* Current job execution time: 0:01:21

- WARNING, job ID JID_845335194463 not marked completed, current job information:

* Name: update:DCIM:INSTALLED#741__BIOS.Setup.1-1
* Job Status: The specified job is in progress.
* Current job execution time: 0:01:37

- WARNING, job ID JID_845335194463 not marked completed, current job information:

* Name: update:DCIM:INSTALLED#741__BIOS.Setup.1-1
* Job Status: The specified job is in progress.
* Current job execution time: 0:01:52

- WARNING, job ID JID_845335194463 not marked completed, current job information:

* Name: update:DCIM:INSTALLED#741__BIOS.Setup.1-1
* Job Status: The specified job is in progress.
* Current job execution time: 0:02:08

- WARNING, job ID JID_845335194463 not marked completed, current job information:

* Name: update:DCIM:INSTALLED#741__BIOS.Setup.1-1
* Job Status: The specified job is in progress.
* Current job execution time: 0:02:23

- WARNING, job ID JID_845335194463 not marked completed, current job information:

* Name: update:DCIM:INSTALLED#741__BIOS.Setup.1-1
* Job Status: The specified job is in progress.
* Current job execution time: 0:02:44

- WARNING, job ID JID_845335194463 not marked completed, current job information:

* Name: update:DCIM:INSTALLED#741__BIOS.Setup.1-1
* Job Status: The specified job is in progress.
* Current job execution time: 0:02:59

- WARNING, job ID JID_845335194463 not marked completed, current job information:

* Name: update:DCIM:INSTALLED#741__BIOS.Setup.1-1
* Job Status: The specified job is in progress.
* Current job execution time: 0:03:15

- WARNING, job ID JID_845335194463 not marked completed, current job information:

* Name: update:DCIM:INSTALLED#741__BIOS.Setup.1-1
* Job Status: The specified job is in progress.
* Current job execution time: 0:03:31

- WARNING, job ID JID_845335194463 not marked completed, current job information:

* Name: update:DCIM:INSTALLED#741__BIOS.Setup.1-1
* Job Status: The specified job is in progress.
* Current job execution time: 0:03:46

- WARNING, job ID JID_845335194463 not marked completed, current job information:

* Name: update:DCIM:INSTALLED#741__BIOS.Setup.1-1
* Job Status: The specified job is in progress.
* Current job execution time: 0:04:02

- WARNING, job ID JID_845335194463 not marked completed, current job information:

* Name: update:DCIM:INSTALLED#741__BIOS.Setup.1-1
* Job Status: The specified job is in progress.
* Current job execution time: 0:04:17

- WARNING, job ID JID_845335194463 not marked completed, current job information:

* Name: update:DCIM:INSTALLED#741__BIOS.Setup.1-1
* Job Status: The specified job is in progress.
* Current job execution time: 0:04:33

- WARNING, job ID JID_845335194463 not marked completed, current job information:

* Name: update:DCIM:INSTALLED#741__BIOS.Setup.1-1
* Job Status: The specified job is in progress.
* Current job execution time: 0:04:48

- WARNING, job ID JID_845335194463 not marked completed, current job information:

* Name: update:DCIM:INSTALLED#741__BIOS.Setup.1-1
* Job Status: The specified job is in progress.
* Current job execution time: 0:05:04

- WARNING, job ID JID_845335194463 not marked completed, current job information:

* Name: update:DCIM:INSTALLED#741__BIOS.Setup.1-1
* Job Status: The specified job is in progress.
* Current job execution time: 0:05:20


- PASS, job ID JID_845335194463 successfully marked completed

- Final detailed job results -

@odata.context: /redfish/v1/$metadata#DellJob.DellJob
@odata.id: /redfish/v1/Managers/iDRAC.Embedded.1/Jobs/JID_845335194463
@odata.type: #DellJob.v1_0_1.DellJob
CompletionTime: 2020-03-18T07:17:57
Description: Job Instance
EndTime: TIME_NA
Id: JID_845335194463
JobState: Completed
JobType: FirmwareUpdate
Message: The specified job has completed successfully.
MessageArgs: []
MessageId: PR19
Name: update:DCIM:INSTALLED#741__BIOS.Setup.1-1
PercentComplete: 100
StartTime: TIME_NOW
TargetSettingsURI: None

**Comment by digi-talo** [comment]
@texroemer First of all thanks for the detailed descirption, highly appreciated.
I followed the exact steps above but it still fails with the same error message.
The DUP I added is `BIOS_004Y7_WN64_2.5.4.EXE`, I verified the content of the Catalog.xml, looks okay:
<summary>
��<?xml version="1.0" encoding="UTF-16LE" standalone="no"?>
<Manifest baseLocation="downloads.dell.com" dateTime="2020-03-18T22:34:30" identifier="e9f4c9be-105b-45dd-9c69-17ae5fcd7da2" releaseID="" version="1.02">
    <ReleaseNotes/>
    <InventoryComponent dateTime="2019-12-27T07:08:19Z" dellVersion="A00" hashMD5="60d563bd437618ddc02471c5176abc3c" osCode="WIN64" path="FOLDER06018518M/1/invcol_HW0HN_WIN64_20_02_00_771_A00.EXE" releaseDate="December 27, 2019" releaseID="HW0HN" schemaVersion="2.0" vendorVersion="20.02.00.771"/>
    <SoftwareBundle bundleID="3BIOS0716BTW64" bundleType="BTW64" dateTime="2020-03-18T22:18:32" identifier="f759f11c-3064-45c5-96ce-2be8dc928941" path="" releaseID="" schemaVersion="" size="28787480" vendorVersion="1.00">
        <Name>
            <Display lang="en">R640</Display>
        </Name>
        <ComponentType value="SBDL">
            <Display lang="en">Dell System Bundle</Display>
        </ComponentType>
        <TargetOSes>
            <OperatingSystem majorVersion="" minorVersion="" osCode="WIN64" osVendor="Microsoft" preinstallationEnvironment="false" spMajorVersion="" spMinorVersion="" suiteMask="0">
                <Display lang="en">Microsoft Windows x64</Display>
            </OperatingSystem>
        </TargetOSes>
        <TargetSystems>
            <Brand key="3" prefix="PE">
                <Display lang="en">PowerEdge</Display>
                <Model systemID="0716" systemIDType="BIOS">
                    <Display lang="en">R640</Display>
                </Model>
            </Brand>
        </TargetSystems>
        <Contents>
            <Package path="BIOS_004Y7_WN64_2.5.4.EXE"/>
        </Contents>
    </SoftwareBundle>
    <SoftwareComponent containerPowerCycleRequired="0" dateTime="2020-01-14T08:50:28" dellVersion="2.5.4" hashMD5="c57b80c2d7bd782d4e100fb772ed1c02" identifier="7d7b643d-3dbf-490d-9d6f-dbd78478ffbd" packageID="004Y7X00-00" packageType="LW64" path="BIOS_004Y7_WN64_2.5.4.EXE" rebootRequired="true" releaseDate="January 13, 2020" releaseID="004Y72.5.4" schemaVersion="1.0" size="28787480" vendorVersion="2.5.4" xmlGenVersion="1.0.3681">
        <Name>
            <Display lang="en"><![CDATA[Dell EMC Server PowerEdge BIOS R740/R740xd/R640/R940/7920R Version 2.5.4]]></Display>
        </Name>
        <ComponentType value="BIOS">
            <Display lang="en"><![CDATA[BIOS]]></Display>
        </ComponentType>
        <Description>
            <Display lang="en"><![CDATA[- Added the Intel Speed Select Technology   Base Frequency (SST-BF) feature. 
- Updated the "Processor and Memory Reference Code" to 0595.D.04.
- Updated a few BIOS Setup help messages.
For more information about specific items added and resolved in this BIOS version, see the Fixes and New and enhanced features sections.]]></Display>
        </Description>
        <LUCategory value="BIOS">
            <Display lang="en"><![CDATA[BIOS]]></Display>
        </LUCategory>
        <Category value="BI">
            <Display lang="en"><![CDATA[BIOS]]></Display>
        </Category>
        <SupportedDevices>
            <RollbackInformation fmpWrapperIdentifier="843cfde2-079c-49b9-a9b6-8ff603d9cf6b" impactsTPMmeasurements="false" rollbackIdentifier="23252cbb-c429-48bf-85b2-dd3b832f0e2d" rollbackTimeout="720" rollbackVolume="MAS022"/>
            <Device componentID="159" embedded="0">
                <Display lang="en"><![CDATA[PowerEdge BIOS]]></Display>
            </Device>
        </SupportedDevices>
        <SupportedSystems>
            <Brand key="80" prefix="PRE">
                <Display lang="en"><![CDATA[Precision]]></Display>
                <Model systemID="0718" systemIDType="BIOS">
                    <Display lang="en"><![CDATA[Precision 7920 XL Rack]]></Display>
                </Model>
            </Brand>
            <Brand key="3" prefix="PE">
                <Display lang="en"><![CDATA[PowerEdge]]></Display>
                <Model systemID="0737" systemIDType="BIOS">
                    <Display lang="en"><![CDATA[R740xd]]></Display>
                </Model>
                <Model systemID="0715" systemIDType="BIOS">
                    <Display lang="en"><![CDATA[R740]]></Display>
                </Model>
                <Model systemID="0728" systemIDType="BIOS">
                    <Display lang="en"><![CDATA[R940]]></Display>
                </Model>
                <Model systemID="0717" systemIDType="BIOS">
                    <Display lang="en"><![CDATA[C4140]]></Display>
                </Model>
                <Model systemID="0716" systemIDType="BIOS">
                    <Display lang="en"><![CDATA[R640]]></Display>
                </Model>
            </Brand>
        </SupportedSystems>
        <InstallInstruction>
            <Display/>
        </InstallInstruction>
        <RevisionHistory>
            <Display/>
        </RevisionHistory>
        <ImportantInfo URL="http://www.dell.com/support/home/us/en/19/Drivers/DriversDetails?driverId=004Y7">
            <Display lang="en"><![CDATA[N/A]]></Display>
        </ImportantInfo>
        <Criticality value="1">
            <Display lang="en"><![CDATA[Recommended-Dell EMC recommends applying this update during your next scheduled update cycle. The update contains feature enhancements or changes that will help keep your system software current and compatible with other system modules (firmware, BIOS, drivers, and software).]]></Display>
        </Criticality>
    </SoftwareComponent>
    <Prerequisites/>
</Manifest>


</summary>

**Comment by texroemer** [comment]
iDRAC will check the repository first and compare against current firmware version on the server and if there is a firmware version difference detected, it will create an update job to perform the update. If the firmware version detected is the same for a device, no update job gets created. 

Example below shows custom repository which has BIOS, NIC and RAID DUPs. BIOS is already at the latest version, NIC and RAID are not at the latest version so when i perform repository update, only NIC and RAID get updated. 


C:\Python38-32>InstallFromRepositoryREDFISH.py -ip 100.65.84.79 -u root -p calvin -g y

- WARNING, current devices detected with firmware version and updateable status -

Device Name: PERC H330 Mini, Firmware Version: 25.5.5.0005, Updatable: True
Device Name: OS COLLECTOR, v5.0, A00, Firmware Version: 5, Updatable: True
Device Name: Disk 5 in Backplane 1 of Integrated RAID Controller 1, Firmware Version: DM06, Updatable: True
Device Name: Disk 0 in Backplane 1 of Integrated RAID Controller 1, Firmware Version: TT31, Updatable: True
Device Name: Power Supply.Slot.1, Firmware Version: 00.32.57, Updatable: True
Device Name: BP14G+ 0:1, Firmware Version: 4.32, Updatable: True
Device Name: iDRAC Service Module Embedded Package, v3.4.0, A00, Firmware Version: 3.4.0, Updatable: True
Device Name: Disk 1 in Backplane 1 of Integrated RAID Controller 1, Firmware Version: AS0E, Updatable: True
Device Name: Disk 2 in Backplane 1 of Integrated RAID Controller 1, Firmware Version: EC02, Updatable: True
Device Name: Disk 3 in Backplane 1 of Integrated RAID Controller 1, Firmware Version: EC02, Updatable: True
Device Name: BOSS-S1, Firmware Version: 2.5.13.3022, Updatable: True
Device Name: Disk 0 on AHCI Controller in slot 1, Firmware Version: E001, Updatable: True
Device Name: BIOS, Firmware Version: 2.5.4, Updatable: True
Device Name: Dell OS Driver Pack, 19.10.12, A00, Firmware Version: 19.10.12, Updatable: True
Device Name: Disk 7 in Backplane 1 of Integrated RAID Controller 1, Firmware Version: K516, Updatable: True
Device Name: Integrated Dell Remote Access Controller, Firmware Version: 4.00.00.00, Updatable: True
Device Name: Dell 64 Bit uEFI Diagnostics, version 4301, 4301A42, 4301.43, Firmware Version: 4301A42, Updatable: True
Device Name: Broadcom Gigabit Ethernet BCM5720 - 18:66:DA:EC:B2:46, Firmware Version: 21.40.21, Updatable: True
Device Name: System CPLD, Firmware Version: 1.0.5, Updatable: True
Device Name: Lifecycle Controller, Firmware Version: 4.00.00.00, Updatable: False


[root@linux R640_repo_latest]# ls -ltr
total 43468
-rwxr--r-- 1 root root 28787480 Mar 18 09:48 BIOS_004Y7_WN64_2.5.4.EXE
-rwxr--r-- 1 root root  7003216 Mar 18 19:54 Network_Firmware_RG25N_WN64_21.60.2_01.EXE
-rwxr--r-- 1 root root  8596504 Mar 18 19:55 SASRAID_Firmware_T23TV_WN64_25.5.6.0009_A12.EXE
-rwxr--r-- 1 root root    52588 Mar 18 20:50 Catalog.xml
[root@linux R640_repo_latest]#




C:\Python38-32>InstallFromRepositoryREDFISH.py -ip 100.65.84.79 -u root -p calvin -i y --ipaddress 100.65.84.150 --sharetype HTTP --sharename updates_http/R640_repo_latest --applyupdate True --rebootneeded True

- WARNING, arguments and values for InstallFromRepository method

ApplyUpdate: True
RebootNeeded: True
IPAddress: 100.65.84.150
ShareType: HTTP
ShareName: updates_http/R640_repo_latest

- PASS: POST command passed for method "InstallFromRepository", status code 202 returned
- PASS, repository job ID JID_846412945017 successfully created
- WARNING, job ID JID_846412945017 not marked completed, current job information:

* Name: Repository Update
* Job Status: Downloading the Catalog.xml update package.
* Current job execution time: 0:00:00


- WARNING, repository package successfully downloaded. If version changed detected for any device, update job ID will get created and execute for that device

- WARNING, job ID JID_846412945017 not marked completed, current job information:

* Name: Repository Update
* Job Status: Package successfully downloaded.
* Current job execution time: 0:00:21


- PASS, job ID JID_846412945017 successfully marked completed

- Final detailed job results -

@odata.context: /redfish/v1/$metadata#DellJob.DellJob
@odata.id: /redfish/v1/Managers/iDRAC.Embedded.1/Jobs/JID_846412945017
@odata.type: #DellJob.v1_0_2.DellJob
CompletionTime: 2020-03-19T11:08:53
Description: Job Instance
EndTime: None
Id: JID_846412945017
JobState: Completed
JobType: RepositoryUpdate
Message: Job completed successfully.
MessageArgs: ['NA']
MessageArgs@odata.count: 1
MessageId: RED001
Name: Repository Update
PercentComplete: 100
StartTime: TIME_NOW
TargetSettingsURI: None



- WARNING, repository update job marked completed. Script will now check to see if any update job(s) were created due to different firmware version change detected

- WARNING, scheduled update job ID detected, server rebooting to apply the update(s)
- WARNING, job ID JID_846413006781 not marked completed, current job information:

* Name: Firmware Update: Network
* Job Status: Task successfully scheduled.
* Current job execution time: 0:00:00

- WARNING, job ID JID_846413006781 not marked completed, current job information:

* Name: Firmware Update: Network
* Job Status: Task successfully scheduled.
* Current job execution time: 0:00:16

- WARNING, job ID JID_846413006781 not marked completed, current job information:

* Name: Firmware Update: Network
* Job Status: Task successfully scheduled.
* Current job execution time: 0:00:31

- WARNING, job ID JID_846413006781 not marked completed, current job information:

* Name: Firmware Update: Network
* Job Status: Job in progress.
* Current job execution time: 0:09:17

- WARNING, job ID JID_846413006781 not marked completed, current job information:

* Name: Firmware Update: Network
* Job Status: Job in progress.
* Current job execution time: 0:09:35


- PASS, job ID JID_846413006781 successfully marked completed

- Final detailed job results -

@odata.context: /redfish/v1/$metadata#DellJob.DellJob
@odata.id: /redfish/v1/Managers/iDRAC.Embedded.1/Jobs/JID_846413006781
@odata.type: #DellJob.v1_0_2.DellJob
CompletionTime: 2020-03-19T11:18:56
Description: Job Instance
EndTime: TIME_NA
Id: JID_846413006781
JobState: Completed
JobType: FirmwareUpdate
Message: Job completed successfully.
MessageArgs: []
MessageArgs@odata.count: 0
MessageId: PR19
Name: Firmware Update: Network
PercentComplete: 100
StartTime: TIME_NOW
TargetSettingsURI: None



- PASS, job ID JID_846413168473 successfully marked completed

- Final detailed job results -

@odata.context: /redfish/v1/$metadata#DellJob.DellJob
@odata.id: /redfish/v1/Managers/iDRAC.Embedded.1/Jobs/JID_846413168473
@odata.type: #DellJob.v1_0_2.DellJob
CompletionTime: 2020-03-19T11:18:56
Description: Job Instance
EndTime: TIME_NA
Id: JID_846413168473
JobState: Completed
JobType: FirmwareUpdate
Message: Job completed successfully.
MessageArgs: []
MessageArgs@odata.count: 0
MessageId: PR19
Name: Firmware Update: SAS RAID
PercentComplete: 100
StartTime: TIME_NOW
TargetSettingsURI: None



Can you attach complete script execution output so i can see if the repository job or update job is failing?

**Comment by texroemer** [comment]
For the BIOS DUP you are using, can you try using the iDRAC GUI update page to validate the DUP can successfully upload and create schedule job? You don't need to reboot the server to run the job, just download and create a scheduled job for next reboot. If this passes, you can then delete the job ID.
