### ISSUE TITLE
Lifecycle Manager loop

### ISSUE THREAD

**Issue by jahedges-tp** [dell/iDRAC-Redfish-Scripting#108]
Issue: If machine is currently booted into the lifecycle manager there is no way to break  the boot process without logging into the console and exiting lifecycle controller.  If you initiate reboot with any REDFISH cmdlet server will simply throw "Lifecycle requested" and go back to the manager. 

Request: Can REDFISH call be added that can break this cycle?

**Comment by texroemer** [comment]
Hi @jahedges-tp 

Currently there is no way remote to gracefully exit F10 LC UI but this is something i'll bring up to my teams at Dell, see if this can get added in future iDRAC release.

Here is a workaround example you can do from Redfish to get out of this state.

1. Server already booted into LC UI (F10), i will try to create BIOS config job which will fail for LC in use.


C:\Python38-32>GetSetBiosAttributesREDFISH.py -ip 192.168.0.120 -u root -p calvin -an Memtest -av Disabled -r n

- WARNING, script will be setting BIOS attributes -

Attribute Name: Memtest, setting new value to: Disabled

- PASS: PATCH command passed to set BIOS attribute pending values and create next reboot config job, status code 202 returned

- PASS, JID_907711874853 next reboot config JID successfully created

- WARNING: JobStatus not scheduled, current status is: New
- WARNING, Lifecycle Controller in use, this job will start when Lifecycle Controller is available. Check overall jobqueue to make sure no other jobs are running and make sure server is either off or out of POST

2. Next i will check to validate server is in LC UI by checking the server status.

C:\Python38-32>GetRemoteServicesAPIStatusREDFISH.py -ip 192.168.0.120 -u root -p calvin

-PASS: POST command passed for GetRemoteServicesAPIStatus method, status code 200 returned

LCStatus: InUse
RTStatus: Ready
**ServerStatus: LCUSC**
Status: NotReady

3. Disable LC state.

C:\Python38-32>SetIdracLcSystemAttributesREDFISH.py -ip 192.168.0.120 -u root -p calvin -s lc -an LCAttributes.1.LifecycleControllerState -av Disabled

- WARNING, changing "LC" attributes -

 Attribute Name: LCAttributes.1.LifecycleControllerState, setting new value to: Disabled

- PASS, Command passed to successfully set "LC" attribute(s), status code 200 returned

- WARNING, getting new attribute values -

Attribute Name: LCAttributes.1.LifecycleControllerState, Attribute Value: Disabled

4. Reboot the server which will not boot into LC since its now disabled.

C:\Python38-32>SetPowerStateREDFISH.py -ip 192.168.0.120 -u root -p calvin -r ForceRestart

- WARNING, setting new server power state to: ForceRestart

- PASS, status code 204 returned, server power state successfully set to "ForceRestart"

5. Verify POST complete, server back in idle state.

C:\Python38-32>GetRemoteServicesAPIStatusREDFISH.py -ip 192.168.0.120 -u root -p calvin

-PASS: POST command passed for GetRemoteServicesAPIStatus method, status code 200 returned

LCStatus: Disabled
RTStatus: Ready
**ServerStatus: HaltedF1/F2/F11Prompt**
Status: NotReady

6. Enable LC state.

C:\Python38-32>SetIdracLcSystemAttributesREDFISH.py -ip 192.168.0.120 -u root -p calvin -s lc -an LCAttributes.1.LifecycleControllerState -av Enabled

- WARNING, changing "LC" attributes -

 Attribute Name: LCAttributes.1.LifecycleControllerState, setting new value to: Enabled

- PASS, Command passed to successfully set "LC" attribute(s), status code 200 returned

- WARNING, getting new attribute values -

Attribute Name: LCAttributes.1.LifecycleControllerState, Attribute Value: Enabled

7. Execute BIOS config job again, now runs. 

C:\Python38-32>GetSetBiosAttributesREDFISH.py -ip 192.168.0.120 -u root -p calvin -an Memtest -av Disabled -r n

- WARNING, script will be setting BIOS attributes -

Attribute Name: Memtest, setting new value to: Disabled

- PASS: PATCH command passed to set BIOS attribute pending values and create next reboot config job, status code 202 returned

- PASS, JID_907716799440 next reboot config JID successfully created

- WARNING: JobStatus not scheduled, current status is: New
- PASS, JID_907716799440 job id successfully scheduled, rebooting the server to apply boot option changes

- WARNING, Current server power state is: On
- PASS, POST command passed to gracefully power OFF server, status code return is 204
- WARNING, script will now verify the server was able to perform a graceful shutdown. If the server was unable to perform a graceful shutdown, forced shutdown will be invoked in 5 minutes
- PASS, GET command passed to verify graceful shutdown was successful and server is in OFF state
- PASS, Command passed to power ON server, status code return is 204
- WARNING: JobStatus not marked completed, current status is: Task successfully scheduled.
- WARNING: JobStatus not marked completed, current status is: Task successfully scheduled.
- WARNING: JobStatus not marked completed, current status is: Task successfully scheduled.
- WARNING: JobStatus not marked completed, current status is: Task successfully scheduled.
- WARNING: JobStatus not marked completed, current status is: Task successfully scheduled.
- WARNING: JobStatus not marked completed, current status is: Task successfully scheduled.
- WARNING: JobStatus not marked completed, current status is: Job in progress.
- WARNING: JobStatus not marked completed, current status is: Job in progress.
- WARNING: JobStatus not marked completed, current status is: Job in progress.
- WARNING: JobStatus not marked completed, current status is: Job in progress.
- WARNING: JobStatus not marked completed, current status is: Job in progress.
- PASS, JID_907716799440 job id successfully completed

**Comment by jahedges-tp** [comment]
Interesting, ok I will have to look at the python scripts, I thought they were just mirror between PowerShell and Python.  That status script is extremely handy.  I will test this out on the next build and report back, thank you.
