### ISSUE TITLE
Mount Virtual media to update BIOS firmware is stuck at keyboard input "Press Enter"

### ISSUE THREAD

**Issue by boopathid** [dell/iDRAC-Redfish-Scripting#119]
Used SetNextOneTimeBootVirtualMediaDeviceOemREDFISH.py to update the firmwares. 
Mounted virtual media, set the boot to virtual media. After the powercycle, the update finishes successfully but waits at screen asking for user to press "Enter" from keyboard to finish BIOS update. I issued powercycle again but it didnt update BIOS firmware. 
Is there any API call or method to solve this issue using Python ?

**Comment by texroemer** [comment]
Hi @boopathid 

Python script SetNextOneTimeBootVirtualMediaDeviceOemREDFISH.py only sets next onetime boot to either virtual floppy or virtual CD, it doesn't update firmware for any device. Did you modify the script or was a separate script called to update the BIOS firmware.

Do you also have a screen capture where it's prompting you to press enter? Firmware update shouldn't prompt you to press enter, i assume there must be an error happening in POST which is asking for interaction.

**Comment by boopathid** [comment]
Hello @texroemer,
I have modified the script. Here what I have done, 
1) Mount the "PER640_BOOTABLE_20.04.00.127.iso" to Virtual CD
Using POST https://<iDrac IP>/redfish/v1/Managers/iDRAC.Embedded.1/VirtualMedia/CD/Actions/VirtualMedia.InsertMedia

2) Using SetNextOneTimeBootVirtualMediaDeviceOemREDFISH.py , set onetime boot to Vir
<img width="1237" alt="Dell iDrac Issue" src="https://user-images.githubusercontent.com/11382366/88404312-95bf3480-cd82-11ea-8ae2-a27016ce1cf4.png">
tual CD. 

3) Reboot the server. 

Upon reboot, the server boots into Virtual CD and starts the upgrade (meant by the bootable ISO). It finishes the upgrade but waits for user input "Enter" though keyboard. (Checked the iDrac UI and it was waiting for the "Enter" key ) as in attached screenshot. 

I tried issuing another "PowerCycle" at this time, thinking it will continue from where it left off. Unfortunately the server Boots up without updating BIOS firmware. 
When I manually pressed "Enter" key from the keyboard, it went ahead and continued the BIOS firmware update. 

So my question is, is there anyway we can script this press "Enter" key function ? Please advice.

**Comment by texroemer** [comment]
Thanks for the image, this helps. You created a custom ISO using DRM to perform the updates. I don't know if it's supported to create an ISO with no user interaction since i don't work on DRM features at Dell. This would need be a question asked on Dell support or community sites where someone from the support team will be able to help you.

**Comment by boopathid** [comment]
Actually its a ISO downloaded from Dell .. https://www.dell.com/support/home/en-us/drivers/driversdetails?driverid=2fx08 . 

Might be Dell has it built this ISO that way to manually press the "Enter" button. But actually, the ISO has other firmwares (iDrac, LSI controller) which gets updated successfully without needing to press "Enter"

**Comment by texroemer** [comment]
Yes, ISO seems to be designed that way due to the server needing a reboot to the apply the BIOS update. iDRAC doesn't need a reboot to apply the update, reason why it doesn't prompt for user interaction.

In your environment, are you looking to update servers to latest firmware for all devices? If yes, have you looked into using iDRAC repository update feature? This feature points a Dell server to a firmware repository, checks the firmware version of all devices in the server against the repository packages and if it detects any version difference, it updates that device. 

See script "InstallFromRepositoryREDFISH.py" for more details. Example below shows executing the script using Dell HTTP firmware repository.

InstallFromRepositoryREDFISH.py -ip 192.168.0.120 -u root -p calvin -i y --ipaddress 143.166.147.76 --sharetype HTTP --applyupdate True --rebootneeded True

**Comment by boopathid** [comment]
We have requirements to be on Specific version of Firmwares to comply security and internal policies. So we dont always update latest and greatest whenever Dell comes up with new version. Usually it takes a while to get vetted out from audit teams for us to proceed with updates. Thats why we picked ISO than the repo. 

And also, iDrac has no internet connection or outgoing traffic. It has to be done locally mounted or internal Share drive.

**Comment by texroemer** [comment]
Ok, makes sense based off the environment you are in.
