### ISSUE TITLE
SystemEraseREDFISH.py  - getting error with Python3

### ISSUE THREAD

**Issue by markatdxb** [dell/iDRAC-Redfish-Scripting#135]
hi, just started testing this script, after starting with following line:
python3 wipe_all.py -ip 10.10.10.10 -u root -p calvin

getting error:
Traceback (most recent call last):
  File "wipe_all.py", line 260, in <module>
    check_supported_idrac_version()
  File "wipe_all.py", line 49, in check_supported_idrac_version
    for i in data['Actions'].keys():
KeyError: 'Actions'

running it on iDrac 8 with the latest 2.75.75.75 FW

**Comment by texroemer** [comment]
Hi @markatdxb 

iDRAC 7/8 does not support OEM SystemErase feature using Redfish, only iDRAC 9. The script error you hit was due to the code was missing a status code check which i've corrected, new script uploaded.

If you want to use SystemErase feature on iDRAC 7/8, you will need to leverage "racadm systemerase" command. 

Thanks
Tex

**Comment by markatdxb** [comment]
Thanks for fix and info
