### ISSUE TITLE
Create new user in idrac with redfish API

### ISSUE THREAD

**Issue by muraliselva10** [dell/iDRAC-Redfish-Scripting#16]
Hello, 

After some analysis I found the way for configuring new user in IDRAC.

import requests
import json
url = 'https://host-rsc/redfish/v1/Managers/iDRAC.Embedded.1/Accounts/3'
plUserName = {'UserName': 'testuser'}
plPass = {'Password': 'calvin'}
plRoleId = {'RoleId': 'Administrator'}
p1Enabled = {'Enabled':True}
headers = {'content-type': 'application/json'}
for payload in plUserName,plPass,plRoleId, p1Enabled:
 response = requests.patch(url, data=json.dumps(payload), headers=headers,verify=False, auth=('root','pass'))
 print(response.text)

With this script I can be able to change the username, password, enabled, role.

But now I need to change the LAN, Serial port, Serial over lan  values. Please suggest how to find the payload for the same.

I don't find any for the same.

{"@odata.context":"/redfish/v1/$metadata#ManagerAccount.ManagerAccount","@odata.id":"/redfish/v1/Managers/iDRAC.Embedded.1/Accounts/3","@odata.type":"#ManagerAccount.v1_0_2.ManagerAccount","Description":"User Account","Enabled":false,"Id":"3","Links":{"Role":{"@odata.id":"/redfish/v1/Managers/iDRAC.Embedded.1/Roles/Administrator"}},"Locked":false,"Name":"User Account","Password":null,"RoleId":"Administrator","UserName":"testuser"}

Thanks.

**Comment by texroemer** [comment]
Hi,

For the attributes you are trying to set now for iDRAC, these will be under "redfish/v1/Managers/iDRAC.Embedded.1/Attributes" URI. I have scripts already created to get and set these attributes.

GetIdracLcSystemAttributesREDFISH.py
SetIdracLcSystemAttributesREDFISH.py

These scripts are only supported for 14G iDRAC9 so if you are using 12G-13G iDRAC7-8, use Server ConfigurationProfile (SCP) scripts instead. 

ExportSystemConfigurationLocalREDFISH.py
ImportSystemConfigurationLocalREDFISH.py

These are easier to use for setting multiple attributes because they will export all attributes locally to your system. You will then modify the exported file with your attributes changes and then import the file back to the iDRAC to apply changes. You can also add user configuration changes to this same exported file and apply all changes at once to the iDRAC. This feature is also helpful when you want to deploy a specific configuration to multiple servers, you edit one export file and then import this file to multiple servers.

Btw, i also created a script to create / delete iDRAC users which i posted today.

Thanks
