### ISSUE TITLE
About the progress of Idrac8 bios provisioning

### ISSUE THREAD

**Issue by Kdy77k** [dell/iDRAC-Redfish-Scripting#166]
I run an bios firmware updating via redfish simple update for Idrac8 and Idrac9.
I find that the Idrac9 server will download the image, deploy and reboot automatically with task-state "completed" and task-Status "OK". On the contrary, the Idrac8 server will download the image, create a redfish scheduled job and wait for administrator rebooting the server. Until administrator reboot the server, the Idrac8 will deploy the image and reboot the server again automatically. 
a. I want to confirm whether the deploying action will just occur after administrator rebooting the server, or not?
b. Could I trigger the Idrac8 to reboot itself automatically via redfish simple update interface for deploying bios image just like what Idrac9 does.
Thank you very much @texroemer

**Comment by texroemer** [comment]
Hi @Kdy77k 

Using iDRAC9, SimpleUpdate action with TransferProtocol, if the device needs a reboot to the apply the update, the server should not automatically reboot but it currently does in iDRAC 4.40. This is a known bug in iDRAC 4.40 because it was not implemented correctly based off the DMTF spec. This issue will be resolved in 5.00 iDRAC which is scheduled to be released this June. In 5.00 iDRAC, in the JSON body for POST, you pass in "@Redfish.OperationApplyTime" parameter with a value of "Immediate". This will automatically reboot the server to apply the update if the device itself needs a server reboot to apply the firmware (device examples: BIOS, storage controller, NIC card).

On iDRAC8, if you want the server to automatically reboot to apply the update and don't need want to execute a separate action to reboot the server (ComputerSystem.Reset), you will have to use OEM action "DellUpdateService.Install". There is currently no DMTF action which supports auto reboot in iDRAC8.

Thanks
