### ISSUE TITLE
Redfish API attributes required for components,no proper document available for the information of the same

### ISSUE THREAD

**Issue by vivekanand553** [dell/iDRAC-Redfish-Scripting#204]
Hello Team,

I need the Racadm commands and attributes which can be used in a playbook for the following components

1. Disable PowerCap on Idrac server.
2. First boot device need to be set to normal.
3. Set Server boot once option enabled.
4. Nic MTU settings,Disable Ipv6.
5. Enable Virtual Console.
6. Enable Virtual Console auto attach.
7. Set Virtual Console to Active X.
8. LCD config Set to 12G.

Thanks for all your help in advance. 

Regards
Vivekanand

**Comment by texroemer** [comment]
Hi @vivekanand553 

All iDRAC attributes can be found in the attribute registry doc linked below. For #4 the only NIC MTU iDRAC attribute is for setting maximum transmission units. Do you mean disable Ipv6 network? 

https://dl.dell.com/content/manual66428237-integrated-dell-remote-access-controller-9-attribute-registry.pdf?language=en-us&ps=true

1. racadm get system.serverpwr.PowerCapSetting
racadm set system.serverpwr.PowerCapSetting Disabled

2. racadm get idrac.serverboot.FirstBootDevice
racadm set idrac.serverboot.FirstBootDevice Normal

3. racadm get idrac.VirtualMedia.BootOnce
racadm set idrac.VirtualMedia.BootOnce Enabled

4. Need clarification 

5. racadm get idrac.virtualconsole.enable
racadm set idrac.virtualconsole.enable Enabled

6. racadm get idrac.virtualconsole.AttachState
racadm set idrac.virtualconsole.AttachState Auto-attach

7. racadm get idrac.virtualconsole.PluginType
racadm set idrac.virtualconsole.PluginType 0

8. racadm get system.lcd.Configuration
racadm set system.lcd.Configuration 1

Thanks
Tex

**Comment by vivekanand553** [comment]
Hello Texromer,

Thank you so much for your kind reply.

For #4: yes the requirement was to set the maximum transmission units for
the Idrac Nic.

For the ipv6 the request was to disable the ipv6 network.

Apart from this request I have an another request in the Local user
settings section to rename the existing root credentials to svsadmin and
set the standard password as ***@***.***

Is there any ansible module which can be leveraged for the above request?

Thanks and Regards.
Vivekanand

**Comment by texroemer** [comment]
racadm get idrac.ipv6.enable
racadm set idrac.ipv6.enable Disabled

racadm get idrac.nic.mtu
racadm set idrac.nic.mtu <integer value>

racadm get idrac.users.3.UserName 
racadm set idrac.users.3.UserName <new username string>

racadm get idrac.users.3.Password
racadm set idrac.users.3.Password <new password string>

3 is the user account ID in the example so change this value to the user account you want to change.


For Ansible, this is owned by another team within Dell which i don't work on. Can you post your question on their GitHub site.

https://github.com/dell/dellemc-openmanage-ansible-modules

Based off the model name you are setting for LCD you are using iDRAC 7/8 firmware. For Redfish support on iDRAC 7/8, the only way to configure these attributes is to leverage Server Configuration Profile (SCP) feature. See example below to configure these settings using Redfish with SCP feature. 

1. First I'll export only System and iDRAC attribute groups since these are the only attributes needed for your workflow. 

C:\Python39>ExportSystemConfigurationLocalREDFISH.py -ip 192.168.0.120 -u root -p calvin -t IDRAC,System

- Job ID "JID_443320297943" successfully created for ExportSystemConfiguration method

- INFO, JobStatus not completed, current status: "Exporting Server Configuration Profile.", percent complete: "5"
- INFO, JobStatus not completed, current status: "Exporting Server Configuration Profile.", percent complete: "10"
- INFO, JobStatus not completed, current status: "Exporting Server Configuration Profile.", percent complete: "10"
- INFO, JobStatus not completed, current status: "Exporting Server Configuration Profile.", percent complete: "10"
- INFO, JobStatus not completed, current status: "Exporting Server Configuration Profile.", percent complete: "10"
- INFO, JobStatus not completed, current status: "Exporting Server Configuration Profile.", percent complete: "10"
- INFO, JobStatus not completed, current status: "Exporting Server Configuration Profile.", percent complete: "10"
- INFO, JobStatus not completed, current status: "Exporting Server Configuration Profile.", percent complete: "10"
- INFO, JobStatus not completed, current status: "Exporting Server Configuration Profile.", percent complete: "10"

- Export locally job ID JID_443320297943 successfully completed
- PASS, final detailed job status results for job ID JID_443320297943 -

@odata.context: /redfish/v1/$metadata#DellJob.DellJob
@odata.id: /redfish/v1/Managers/iDRAC.Embedded.1/Jobs/JID_443320297943
@odata.type: #DellJob.v1_0_1.DellJob
CompletionTime: 2022-02-08T08:54:38
Description: Job Instance
EndTime: None
Id: JID_443320297943
JobState: Completed
JobType: ExportConfiguration
Message: Successfully exported Server Configuration Profile
MessageArgs: []
MessageId: SYS043
Name: Export Configuration
PercentComplete: 100
StartTime: TIME_NOW
TargetSettingsURI: None

- Exported attributes also saved in file: 2022-2-8_9725_export.xml

2. Next step is to edit the SCP file exported with attribute changes. The SCP file will contain all iDRAC and System attributes but for this workflow, i removed all attributes not needed to better show the edited SCP file which you can use this same file for configuring your servers. If you are not trying to change user account 3, change the ID value before trying to import the SCP file. 

<SystemConfiguration>  
<Component FQDD="System.Embedded.1"> 
<Attribute Name="LCD.1#Configuration">Model Name</Attribute> 
 <Attribute Name="ServerPwr.1#PowerCapSetting">Disabled</Attribute> 
 </Component> 
 <Component FQDD="iDRAC.Embedded.1"> 
 <Attribute Name="Users.3#UserName">user3</Attribute> 
 <Attribute Name="Users.3#Password">P@ssw0rd</Attribute> 
 <Attribute Name="VirtualConsole.1#Enable">Enabled</Attribute> 
 <Attribute Name="VirtualConsole.1#PluginType">Active X</Attribute> 
 <Attribute Name="VirtualConsole.1#AttachState">Auto-Attach</Attribute>
 <Attribute Name="VirtualMedia.1#BootOnce">Enabled</Attribute> 
 <Attribute Name="NIC.1#MTU">1500</Attribute> 
 <Attribute Name="IPv6.1#Enable">Disabled</Attribute> 
 <Attribute Name="ServerBoot.1#FirstBootDevice">Normal</Attribute>  
</Component> 
</SystemConfiguration> 

3. Now i'll import this SCP file to apply attribute changes. 

C:\Python39>ImportSystemConfigurationLocalFilenameREDFISH.py -ip 192.168.0.120 -u root -p calvin -t IDRAC,System -f 2022-2-8_9725_export.xml

- PASS, JID_443334754810 successfully created for ImportSystemConfiguration method
- PASS, job ID JID_443334754810 successfully marked completed

Message: Successfully imported and applied Server Configuration Profile.
MessageArgs: []
MessageArgs@odata.count: 0
MessageId: SYS053

- JID_443334754810 completed in: 0:00:07

Thanks
Tex
