### ISSUE TITLE
how to use scripting to control ntp(Network Time Protocol)

### ISSUE THREAD

**Issue by scut33** [dell/iDRAC-Redfish-Scripting#21]
I want to use python script to control idrac ntp settings, but i can't find the related node. help me, thanks.

**Comment by texroemer** [comment]
Hi,

On iDRAC 9, iDRAC NTP settings are under URI "/redfish/v1/Managers/iDRAC.Embedded.1/Attributes". The NTP attributes listed will be:

NTPConfigGroup.1.NTP1 
NTPConfigGroup.1.NTP2 
NTPConfigGroup.1.NTP3 
NTPConfigGroup.1.NTPEnable 
NTPConfigGroup.1.NTPMaxDist

Use Python script "GetIdracLcSystemAttributesREDFISH.py" to GET these attributes and then for SET, use Python script "SetIdracLcSystemAttributesREDFISH.py"

On iDRAC 7/8, you will need to use Server Configuration Profile (SCP) feature to get and set these attributes since URI "/redfish/v1/Managers/iDRAC.Embedded.1/Attributes" is not supported on this iDRAC version. 

Use python script "ExportSystemConfigurationLocalREDFISH.py" with argument "-t iDRAC" to GET these iDRAC attributes and then for SET, use python script "ImportSystemConfigurationLocalREDFISH.py".

**Comment by texroemer** [comment]
No problem,  glad to help!
