### ISSUE TITLE
Redfish not accessible after upgrading to 2.83.83.83

### ISSUE THREAD

**Issue by Iznik285** [dell/iDRAC-Redfish-Scripting#214]
Hi Tex,

I hope you can help with this issue. 

I've upgraded from 2.82.82.82 to 2.83.83.83 on a Dell PowerEdge R430 with iDrac8 card. Following the upgrade I am unable to use Redfish to access the iDrac card. 

If I simplify then I can access https://\<ipaddr\>/redfish/v1 using Chrome but if I try to access https://\<ipaddr\>/redfish/v1/System I get  This site can't be reached error. If I try the same on an iDrac with 2.82.82.82 I get an authentication box and I can get the details.

Any help you can provide would be gratefully received.

Regards

Jason

**Comment by texroemer** [comment]
Hi Jason,

I was able to repro this issue in my lab with iDRAC 2.83 and Chrome. I've escalated this issue to iDRAC internal teams, will let you know once i find out more details. As a workaround for now, you can use other browsers like Firefox which doesn't have this issue.

Thanks
Tex

**Comment by droorda** [comment]
Not sure if this helps, but firefox does not have the issue, just posh and chromium based browsers

**Comment by texroemer** [comment]
Hi @droorda 

Thanks for also reporting the issue. As a workaround, you can either rollback iDRAC to 2.82 to use Powershell or stay with 2.83, use any browser besides Chrome to run GET requests.

If your servers need to run 2.83 and use Powershell for your workflows, please escalate a support case to Dell Tech Support. They should be able to supply you with an iDRAC firmware that has the fix for this issue.

Thanks
Tex

**Comment by Iznik285** [comment]
Hi Tex,

I logged a call with Dell Tech Support and they provided a firmware version 2.83.100.83. I've tested this and can confirm it resolves the issue. 

Many thanks for your help.

Regards

Jason

**Comment by texroemer** [comment]
Hi @Iznik285 

Good to hear you were able to get iDRAC version 2.83.100.83 from Dell Tech Support and confirmed it resolved the issue.

Thanks
Tex
