### ISSUE TITLE
how to set idrac Datetime and timezone

### ISSUE THREAD

**Issue by scut33** [dell/iDRAC-Redfish-Scripting#27]
I want  to modify the idrac datetime and timezone, how to use python to set it, help me, thanks

**Comment by texroemer** [comment]
Hi @scut33 

To change the iDRAC timezone, you will want to set iDRAC attribute "Time.1.Timezone" using script "SetIdracLcSystemAttributesREDFISH.py". Example of dictionary passed in for PATCH command to set timezone attribute:

file_attributes_dict = {"Time.1.Timezone":"CST6CDT"}

To modify the iDRAC date and time, the only iDRAC interface which currently supports this is WSMAN "ManageTime" method. But if you do set the iDRAC date and time using this WSMAN method, then reboot the server and the BIOS date and time is not in sync with this date and time you just set, iDRAC's current date and time will get overwritten with BIOS date and time. iDRAC date and time is always going to get synced with BIOS date and time during a host reboot. 

Because of this behavior, its recommended to go into F2 System Setup and configure the date and time for BIOS. By making this change in F2, settings will be saved and server reboot, run POST and once complete, iDRAC date and time will now be updated and also be in sync with BIOS.

**Comment by scut33** [comment]
thanks

**Comment by greatwall01** [comment]
Lifecycle Controller hardware | 2.50.50.50 can't support "https://%s/redfish/v1/Managers/iDRAC.Embedded.1/Attributes" command,it response error

**Comment by texroemer** [comment]
@greatwall01 

Hi, yes you are correct, URI "redfish/v1/Managers/iDRAC.Embedded.1/Attributes" is not supported on iDRAC 7/8, only supported on iDRAC 9. If you want to set iDRAC attributes with iDRAC 7/8, you must use OEM Server Configuration Profile feature. 

Example below is executing Python script "ImportSystemConfigurationLocalREDFISH.py" to set iDRAC time zone along with the payload i passed in for POST command.

payload = {"ShutdownType":"Forced","ImportBuffer":"<SystemConfiguration><Component FQDD=\"iDRAC.Embedded.1\"><Attribute Name=\"Time.1#Timezone\">CST6CDT</Attribute></Component></SystemConfiguration>","ShareParameters":{"Target":"All"}}

C:\Python27>ImportSystemConfigurationLocalREDFISH.py -ip 192.168.0.120 -u root -p calvin

- JID_350974618511 successfully created for ImportSystemConfiguration method

- Job not marked completed, current status is: Running
- Message: Importing Server Configuration Profile.

- PASS, job ID JID_350974618511 successfully marked completed


- Detailed job results for job ID JID_350974618511

@odata.type: #DellJob.v1_0_0.DellJob
JobState: Completed
Description: Job Instance
TargetSettingsURI: None
MessageArgs: []
CompletionTime: 2018-08-24T02:57:44
PercentComplete: 100
StartTime: TIME_NOW
MessageId: SYS053
Message: Successfully imported and applied Server Configuration Profile.
EndTime: None
Id: JID_350974618511
JobType: ImportConfiguration
Name: Import Configuration

- JID_350974618511 completed in: 0:00:06

- Config results for job ID JID_350974618511

@odata.type: #DellManager.v1_0_0.ServerConfigurationProfileResults
Name: Time.1#Timezone
ErrCode: 0
OldValue: EST
DisplayValue: Time Zone String
NewValue: CST6CDT

**Comment by scut33** [comment]
thanks a lot, great help!
