### ISSUE TITLE
run ImportSystemConfigurationLocalREDFISH.py get html code 503

### ISSUE THREAD

**Issue by scut33** [dell/iDRAC-Redfish-Scripting#28]
hi:
    I imitate ImportSystemConfigurationLocalREDFISH.py and send a request to  v1/Managers/iDRAC.Embedded.1/Actions/Oem/EID_674_Manager.ImportSystemConfiguration, bug got a html code 503, what the problem means? how to solve it?
  help me, thanks a lot

**Comment by texroemer** [comment]
503 status code refers to internal error and issue with processing the request. 

Can you tell me which arguments you passed in when executing the script and also the error message details?

Here's an example of executing the script and passing in minimum required arguments:

C:\Python27>ImportSystemConfigurationLocalFilenameREDFISH.py -ip 192.168.0.120 -u root -p calvin -t all -f 2018-8-27_13594_export.xml

- JID_350721942195 successfully created for ImportSystemConfiguration method

- Job not marked completed, current status is: Running
- Message: Importing Server Configuration Profile.

- PASS, job ID JID_350721942195 successfully marked completed


- Detailed job results for job ID JID_350721942195

@odata.type: #DellJob.v1_0_0.DellJob
JobState: Completed
Description: Job Instance
TargetSettingsURI: None
MessageArgs: []
CompletionTime: 2018-08-23T19:56:37
PercentComplete: 100
StartTime: TIME_NOW
MessageId: SYS053
Message: Successfully imported and applied Server Configuration Profile.
EndTime: None
Id: JID_350721942195
JobType: ImportConfiguration
Name: Import Configuration

- JID_350721942195 completed in: 0:00:06

- Config results for job ID JID_350721942195

@odata.type: #DellManager.v1_0_0.ServerConfigurationProfileResults
Name: Telnet.1#Enable
ErrCode: 0
OldValue: Enabled
DisplayValue: Telnet Enable
NewValue: Disabled

**Comment by znqiao** [comment]
Hi, texroemer 
Please see the details below:

**what dictionary you passed in for POST command?**
payload = {"ImportBuffer":"<SystemConfiguration><Component FQDD=\"iDRAC.Embedded.1\"><Attribute Name=\"IPMILan.1#AlertEnable\">Enabled</Attribute></Component></SystemConfiguration>","ShareParameters":{"Target":"All"}}


**which arguments you passed in when executing the script**
[Unauthorized System] node30@node30-os:~/zengyq$ python ImportSystemConfigurationLocalREDFISH.py -ip 192.168.0.48 -u root -p xxx
<Response [503]>

- FAIL: detailed error message: 

(the end)



**the error message details for status code 503?**
no error message


PS:
1. https://192.168.0.48/redfish/v1/EventService
...
     "ServiceEnabled": false, 
     "Status": {
          "Health": "OK", 
          "HealthRollup": "OK", 
          "State": "Disabled"
     },
...

**Comment by texroemer** [comment]
@znqiao 

Can you try to execute another POST command to verify this works? This will tell us if its either a script issue or communication issue.

You can try using script "SetPowerStateREDFISH.py" to reboot the server.

Example:

C:\Python27\master_scripts_modified>SetPowerStateREDFISH.py 192.168.0.120 root calvin GracefulRestart

- Current server power state is: On, setting new server power state to: GracefulRestart

- PASS, status code 204 returned, server power state successfully set to "GracefulRestart"

**Comment by znqiao** [comment]
Hi, @texroemer

Thank you very much and please see below:

[Unauthorized System] node30@node30-os:~/zengyq$ python SetPowerStateREDFISH.py 192.168.0.48 root xxx  GracefulRestart

- Current server power state is: On, setting new server power state to: GracefulRestart

- PASS, status code 204 returned, server power state successfully set to "GracefulRestart"


And here are what we have done:
1. Our initial goal is to enable the EventSevice

2. We tried this script and it works perfect:
$python SubmitTestEventREDFISH.py -ip 192.168.0.48 -u root -p xxx -c y -D https://192.168.0.30 -E Alert
- WARNING, iDRAC version detected does not support PATCH to set iDRAC attributes, executing Server Configuration Profile feature set iDRAC attribute "IPMILan.1#AlertEnable" locally

- JID_301315787490 successfully created for ImportSystemConfiguration method

- Job ID = JID_301315787490
- Name = Import Configuration
- Message = No changes were applied since the current component configuration matched the requested configuration.
- PASS, POST command passed, status code 201 returned, subscription successfully set for EventService

4. We got the events we wanted.

5. We enabled and  disabled the EventService for test
Enable:
payload = {"ImportBuffer":"<Component FQDD="iDRAC.Embedded.1"><Attribute Name="IPMILan.1#AlertEnable">Enabled","ShareParameters":{"Target":"All"}}

Disable:
payload = {"ImportBuffer":"<Component FQDD="iDRAC.Embedded.1"><Attribute Name="IPMILan.1#AlertEnable">Disabled","ShareParameters":{"Target":"All"}}


6. But someday everything changed：
$python SubmitTestEventREDFISH.py -ip 192.168.0.48 -u root -p xxx -c y -D http://192.168.0.30 -E Alert

- WARNING, iDRAC version detected does not support PATCH to set iDRAC attributes, executing Server Configuration Profile feature set iDRAC attribute "IPMILan.1#AlertEnable" locally

- FAIL: detailed error message: 

We printed the response code and it was：
<Response [503]> 

7. Other settings failed either, such as ImportSystemConfigurationLocalREDFISH.py.( Response [503]).

8. GET works fine.

Please help. Thanks a lot.

**Comment by texroemer** [comment]
@znqiao 

Can you download latest script version from GitHub (ImportSystemConfigurationLocalREDFISH.py) and try to see if issue has been resolved? 

Thanks

**Comment by texroemer** [comment]
@znqiao 

Thanks for trying the new script. What iDRAC version do you have installed? Do you have latest 2.60 version?

Can you also try these steps and see if it fixes the issue?

1. SSH to the iDRAC, at the admin prompt type "racadm racreset" which is going to reset the iDRAC.
2. Wait 5 minutes, this will make sure the iDRAC is fully back up after the reset.
3. Try import Redfish script, see if it works now.

**Comment by znqiao** [comment]
Hi, @texroemer

Good news! I have tried your steps and it works!
(Also the latest script version of ImportSystemConfigurationLocalREDFISH.py)

[Unauthorized System] root@node30-os:/home/node30/zengyq# python ImportSystemConfigurationLocalREDFISH.py -ip 192.168.0.48 -u root -p xxx
{'cookies': <RequestsCookieJar[]>, '_content': '', 'headers': {'Content-Length': '0', 'Accept-Ranges': 'bytes', 'Keep-Alive': 'timeout=60, max=199', 'Server': 'Appweb/4.5.4', 'Connection': 'Keep-Alive', 'Location': '/redfish/v1/TaskService/Tasks/JID_355144988817', 'Cache-Control': 'no-cache', 'Date': 'Wed, 29 Aug 2018 03:48:18 GMT', 'OData-Version': '4.0', 'Access-Control-Allow-Origin': '*', 'Content-Type': 'application/json;odata.metadata=minimal;charset=utf-8'}, 'url': u'https://192.168.0.48/redfish/v1/Managers/iDRAC.Embedded.1/Actions/Oem/EID_674_Manager.ImportSystemConfiguration', 'status_code': 202, '_content_consumed': True, 'encoding': 'utf-8', 'request': <PreparedRequest [POST]>, 'connection': <requests.adapters.HTTPAdapter object at 0x7fac05c350>, 'elapsed': datetime.timedelta(0, 14, 920413), 'raw': <requests.packages.urllib3.response.HTTPResponse object at 0x7fabff15d0>, 'reason': 'Accepted', 'history': []}

- JID_355144988817 successfully created for ImportSystemConfiguration method

- PASS, job ID JID_355144988817 successfully marked completed


- Detailed job results for job ID JID_355144988817

@odata.type: #DellManager.v1_0_0.DellManager
Jobs: {u'@odata.id': u'/redfish/v1/Managers/iDRAC.Embedded.1/Jobs'}

- JID_355144988817 completed in: 0:00:09

- Config results for job ID JID_355144988817

@odata.type: #DellManager.v1_0_0.ServerConfigurationProfileResults
Name: Time.1#Timezone
ErrCode: 0
OldValue: Europe/Vatican
DisplayValue: Time Zone String
NewValue: CST6CDT


And the iDRAC version we are using now is 2.50.50.50. 
It seems that we don't have the latest 2.60. 
So do we need to upgrade or not? And how should we get that?

Thank you so much for your help!

**Comment by texroemer** [comment]
Yes, it's always recommended to use latest firmware versions. Each new iDRAC version will have bug fixes along with support for new Redfish features. In 2.60, examples would be we added support for Redfish schema storage and network properties. On the download page under Fixes & Enhancements section, you will see all the details about this firmware release.

2.60 iDRAC is posted on Dell support site for download. Here's the link:

https://www.dell.com/support/home/us/en/04/drivers/driversdetails?driverId=CX8N2

Good to hear script now works and glad to help out!
