### ISSUE TITLE
iDRAC per FQDN via Redfish 

### ISSUE THREAD

**Issue by downtownle** [dell/iDRAC-Redfish-Scripting#303]
Hello Texas,

if you have and ideas to use redfish for it without racadm let us know.
16G System with idrac9 latest firmware level installed.

We are currently trying to address the iDRACs via FQDN because we don't want them via IP addresses. Unfortunately we get this nice error:
 
The iDRAC is reset to factory default and got its IP address via DHCP.
There is also an entry in your community about this:
https://www.dell.com/community/en/conversations/systems-management-general/idrac9-6000-and-redfish/647f9dc9f4ccf8a8de23c724

It is a security feature that the header is checked and this check fails because DNS Domain is not configured.
How do we get ahead here without addressing the iDRACs via IP address?
![screenshot](https://github.com/dell/iDRAC-Redfish-Scripting/assets/156846636/1025193f-ca3f-4448-99c9-91de414910b4)

**Comment by texroemer** [comment]
Hi @downtownle 

Your iDRAC FQDN string are you able to use it to access the iDRAC GUI and only Redfish curl command is failing or unable to access the iDRAC using any interface?

Also based off the article link did you try to disable hot header check in iDRAC and curl command still fails?

Thanks
Tex

**Comment by downtownle** [comment]
Hello Texas,

I had thought there was a curl redfish command you could recommend to turn it off or on before resetting the idrac to get around it?
Kind of, turn off host header check
Reset idrac9
Switch it back on later if possible host header check.
I can currently only find racadm commands to deactivate it and set DNS entry.

**Comment by texroemer** [comment]
GET and PATCH example for iDRAC attribute WebServer.1.HostHeaderCheck.

```
[root@localhost]# curl -k -X GET -u root:calvin 'https://idrac-BZ01345/redfish/v1/Managers/iDRAC.Embedded.1/Oem/Dell/DellAttributes/iDRAC.Embedded.1?$select=Attributes/WebServer.1.HostHeaderCheck' --insecure | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   274  100   274    0     0    200      0  0:00:01  0:00:01 --:--:--   200
{
  "@odata.context": "/redfish/v1/$metadata#DellAttributes.DellAttributes",
  "@odata.id": "/redfish/v1/Managers/iDRAC.Embedded.1/Oem/Dell/DellAttributes/iDRAC.Embedded.1",
  "@odata.type": "#DellAttributes.v1_0_0.DellAttributes",
  "Attributes": {
    "WebServer.1.HostHeaderCheck": "Enabled"
  }
}

[root@localhost]# curl -k -X PATCH -u root:calvin 'https://idrac-BZ01345/redfish/v1/Managers/iDRAC.Embedded.1/Oem/Dell/DellAttributes/iDRAC.Embedded.1' --insecure -d '{"Attributes":{"WebServer.1.HostHeaderCheck":"Disabled"}}' -i -H "Content-Type: application/json"
HTTP/1.1 200 OK
Date: Tue, 14 May 2024 02:47:44 GMT
Server: Apache
OData-Version: 4.0
Cache-Control: no-cache
X-Frame-Options: DENY
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
Content-Length: 506
Vary: Accept-Encoding
Content-Type: application/json;odata.metadata=minimal;charset=utf-8

{"@Message.ExtendedInfo":[{"Message":"The request completed successfully.","MessageArgs":[],"MessageArgs@odata.count":0,"MessageId":"Base.1.12.Success","RelatedProperties":[],"RelatedProperties@odata.count":0,"Resolution":"None","Severity":"OK"},{"Message":"The operation successfully completed.","MessageArgs":[],"MessageArgs@odata.count":0,"MessageId":"IDRAC.2.9.SYS413","RelatedProperties":[],"RelatedProperties@odata.count":0,"Resolution":"No response action is required.","Severity":"Informational"}]}

[root@localhost]# curl -k -X GET -u root:calvin 'https://idrac-BZ01345/redfish/v1/Managers/iDRAC.Embedded.1/Oem/Dell/DellAttributes/iDRAC.Embedded.1?$select=Attributes/WebServer.1.HostHeaderCheck' --insecure | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   275  100   275    0     0    222      0  0:00:01  0:00:01 --:--:--   222
{
  "@odata.context": "/redfish/v1/$metadata#DellAttributes.DellAttributes",
  "@odata.id": "/redfish/v1/Managers/iDRAC.Embedded.1/Oem/Dell/DellAttributes/iDRAC.Embedded.1",
  "@odata.type": "#DellAttributes.v1_0_0.DellAttributes",
  "Attributes": {
    "WebServer.1.HostHeaderCheck": "Disabled"
  }
}
```

Thanks
Tex

**Comment by downtownle** [comment]
That doesn't really help me. Because I can't get to the iDRAC via FQDN.
What needs to be set via DHCPv6 for it to work?

[a758240@m4bxvmvs02cd ~]$ curl -k -X GET -u root:calvin '[https://bn461com5i6x.inf.ref.bm4x.telekom.de/redfish/v1/Managers/iDRAC.Embedded.1/Oem/Dell/DellAttributes/iDRAC.Embedded.1?$select=Attributes/WebServer.1.HostHeaderCheck [bn461com5i6x.inf.ref.bm4x.telekom.de]](https://urldefense.com/v3/__https:/bn461com5i6x.inf.ref.bm4x.telekom.de/redfish/v1/Managers/iDRAC.Embedded.1/Oem/Dell/DellAttributes/iDRAC.Embedded.1?$select=Attributes*WebServer.1.HostHeaderCheck__;Lw!!LpKI!gdp1r_u7qd5oaILu_MhhsxP4JxVkAdvQqBS3q6c8UUPt15aEThEaub9Xxv42nvQp7xue0P-6hmAYgFB9ze8l3Rw$)' --insecure | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   638  100   638    0     0   3987      0 --:--:-- --:--:-- --:--:--  3987
{
  "error": {
    "code": "Base.1.8.GeneralError",
    "message": "A general error has occurred. See ExtendedInfo for more information.",
    "@Message.ExtendedInfo": [
      {
        "@odata.type": "#Message.v1_1_0.Message",
        "MessageId": "Base.1.8.QueryNotSupported",
        "Description": "Indicates that query is not supported on the implementation.",
        "Message": "Querying is not supported by the implementation.",
        "Severity": "Warning",
        "Resolution": "Remove the query parameters and resubmit the request if the operation failed."
      }
    ]
  }
}
[a758240@m4bxvmvs02cd ~]$

I also get an error via the browser:
![screenshot](https://github.com/dell/iDRAC-Redfish-Scripting/assets/156846636/7db8340e-5b31-4bc3-a534-ecc89495e92e)

**Comment by texroemer** [comment]
Can you confirm you can access GUI and run Redfish calls using iDRAC IPv4 address? Also can you ping your iDRAC DNS name and confirm ping request passes, returns the IPv4 address.

Thanks
Tex

**Comment by downtownle** [comment]
In the test we are currently using IPv4, 
![screenshot2](https://github.com/dell/iDRAC-Redfish-Scripting/assets/156846636/76b49091-5472-401b-85e9-df397d4bbc56)
later in production it will be IPv6 only.

A ping works:

[a758240@m4bxvmvs02cd ~]$ ping bn461com5i6x.inf.ref.bm4x.telekom.de
PING bn461com5i6x.inf.ref.bm4x.telekom.de (10.1.3.9) 56(84) bytes of data.
64 bytes from 10.1.3.9 (10.1.3.9): icmp_seq=1 ttl=57 time=12.8 ms

When you call WebGUI this is what happens:

**Comment by texroemer** [comment]
Using IPv4 address can you run Redfish GET and PATCH calls for attribute WebServer.1.HostHeaderCheck, confirm this works. If yes can you disable this attribute and then try accessing iDRAC again using iDRAC DNS name.

Thanks
Tex

**Comment by downtownle** [comment]
yes, if we use the IPv4 address, then it works. But we want to go beyond the name, otherwise it makes no sense for us to give the iDRAC a name.

All automation is based on names, so IPv4 and IPv6 can act independently.

**Comment by texroemer** [comment]
Can you please try using IPv4 address to run PATCH to disable host header check, then try any GET command using DNS name and confirm it passes. 

Example:

```
[root@localhost]# curl -k -X PATCH -u root:calvin 'https://192.168.0.120/redfish/v1/Managers/iDRAC.Embedded.1/Oem/Dell/DellAttributes/iDRAC.Embedded.1' --insecure -d '{"Attributes":{"WebServer.1.HostHeaderCheck":"Disabled"}}' -i -H "Content-Type: application/json"
HTTP/1.1 200 OK
Date: Tue, 14 May 2024 02:47:44 GMT
Server: Apache
OData-Version: 4.0
Cache-Control: no-cache
X-Frame-Options: DENY
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
Content-Length: 506
Vary: Accept-Encoding
Content-Type: application/json;odata.metadata=minimal;charset=utf-8

{"@Message.ExtendedInfo":[{"Message":"The request completed successfully.","MessageArgs":[],"MessageArgs@odata.count":0,"MessageId":"Base.1.12.Success","RelatedProperties":[],"RelatedProperties@odata.count":0,"Resolution":"None","Severity":"OK"},{"Message":"The operation successfully completed.","MessageArgs":[],"MessageArgs@odata.count":0,"MessageId":"IDRAC.2.9.SYS413","RelatedProperties":[],"RelatedProperties@odata.count":0,"Resolution":"No response action is required.","Severity":"Informational"}]}

[root@localhost]# curl -k -X GET -u root:calvin 'https://idrac-BZ01345/redfish/v1/Managers/iDRAC.Embedded.1/Oem/Dell/DellAttributes/iDRAC.Embedded.1?$select=Attributes/WebServer.1.HostHeaderCheck' --insecure | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   275  100   275    0     0    222      0  0:00:01  0:00:01 --:--:--   222
{
  "@odata.context": "/redfish/v1/$metadata#DellAttributes.DellAttributes",
  "@odata.id": "/redfish/v1/Managers/iDRAC.Embedded.1/Oem/Dell/DellAttributes/iDRAC.Embedded.1",
  "@odata.type": "#DellAttributes.v1_0_0.DellAttributes",
  "Attributes": {
    "WebServer.1.HostHeaderCheck": "Disabled"
  }
}
```

Thanks
Tex

**Comment by downtownle** [comment]
Hello Texas,

which fields must be filled with DHCP IPV4 and IPV6 DHCP in the IDRAC9 so that the host header check works and you can access it by name?
The customer would like to know which fields must be filled and how you can set them correctly with Redfish Terraform.
This should be possible with IPV4 and IPV6 only.
Can anyone of you provide information’s to this topic?
A Screenshot or Redfish field output are okay, but we need this for all fields which are required for this function to work well?

**Comment by texroemer** [comment]
Hi @downtownle 

Please see article below which goes into detail about host header check iDRAC behavior.

https://www.dell.com/support/kbdoc/en-us/000193619/http-https-fqdn-connection-failures-on-idrac9-firmware-version-5-10-00-00

Thanks
Tex

**Comment by downtownle** [comment]
Hello Texas,

who can help me with the question which the customer would like to have answered?

Topic: HTTPS-Hostheader
Can the fields "DNSRacName" and "DNSDomainName" also be filled by DHCP v6? If so, which DHCP options must be set for this?

**Comment by downtownle** [comment]
try to solve it over idm module

**Comment by alexdatsko** [comment]
Today is my first day with Redfish so bear with me.  Unfortunately I can GET just fine but cannot PATCH the new setting, keeps telling me malformed json but I can parse the same string with JQ... I am on iDRAC 9  7.10.90.00 (Build 27)

GET returns:

curl.exe -sk -X GET -u "$combined" "https://$($dracip):$($dracport)/redfish/v1/Managers/iDRAC.Embedded.1/Oem/Dell/DellAttributes/iDRAC.Embedded.1?`$select=Attributes/WebServer.1.HostHeaderCheck"

{"@odata.context":"/redfish/v1/$metadata#DellAttributes.DellAttributes","@odata.id":"/redfish/v1/Managers/iDRAC.Embedded.1/Oem/Dell/DellAttributes/iDRAC.Embedded.1","@odata.type":"#DellAttributes.v1_0_0.DellAttributes","Attributes":{"WebServer.1.HostHeaderCheck":"Enabled"}}

PATCH returns:

curl.exe -sk -X PATCH -u "$combined" "https://$($dracip):$($dracport)/redfish/v1/Managers/iDRAC.Embedded.1/Oem/Dell/DellAttributes/iDRAC.Embedded.1" -H "Content-Type: application/json" -d '{"Attributes":{"WebServer.1.HostHeaderCheck":"Disabled"}}'

HTTP/1.1 400 Bad Request
Date: Thu, 23 Jan 2025 23:20:06 GMT
Server: Apache
OData-Version: 4.0
Cache-Control: no-cache
X-Frame-Options: DENY
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
Content-Length: 1016
Connection: close
Content-Type: application/json;odata.metadata=minimal;charset=utf-8

{"error":{"@Message.ExtendedInfo":[{"Message":"Unable to complete the operation because the JSON data format entered is invalid.","MessageArgs":[],"MessageArgs@odata.count":0,"MessageId":"IDRAC.2.9.SYS405","RelatedProperties":[],"RelatedProperties@odata.count":0,"Resolution":"Do the following and the retry the operation: 1) Enter the correct JSON data format and retry the operation. 2) Make sure that no syntax error is present in JSON data format. 3) Make sure that a duplicate key is not present in JSON data format.","Severity":"Critical"},{"Message":"The request body submitted was malformed JSON and could not be parsed by the receiving service.","MessageArgs":[],"MessageArgs@odata.count":0,"MessageId":"Base.1.12.MalformedJSON","RelatedProperties":[],"RelatedProperties@odata.count":0,"Resolution":"Ensure that the request body is valid JSON and resubmit the request.","Severity":"Critical"}],"code":"Base.1.12.GeneralError","message":"A general error has occurred. See ExtendedInfo for more information"}}

Also tried what I'd expect from the GET:

-d '{"@odata.context":"/redfish/v1/$metadata#DellAttributes.DellAttributes","@odata.id":"/redfish/v1/Managers/iDRAC.Embedded.1/Oem/Dell/DellAttributes/iDRAC.Embedded.1","@odata.type":"#DellAttributes.v1_0_0.DellAttributes","Attributes":{"WebServer.1.HostHeaderCheck":"Disabled"}}'

And this gives the same malformed JSON error. What might I be doing wrong? I replaced all characters that might be bad unicode representations etc, that can cause encoding issues. Not sure what else it could be

**Comment by alexdatsko** [comment]
Also, since this is windows, in case its definitely formatting, I've tried the 2 formats below which gave the same response. Also tried changing "Disabled" to "disabled","0",0,false, etc. No luck so far.

https://stackoverflow.com/questions/37806096/why-do-i-get-a-malformed-json-in-request-body-in-this-curl-call

# On Windows
--data "{\"purge_everything\":true}"

# On Windows works as well
--data "{""purge_everything"":true}"

**Comment by texroemer** [comment]
Hi @alexdatsko 

When using CURL in Windows, you have to escape the double quotes in the payload body. Example below showing PATCH passing.

```
C:\>curl -X PATCH "https://192.168.0.120/redfish/v1/Managers/iDRAC.Embedded.1/Oem/Dell/DellAttributes/iDRAC.Embedded.1" -u root:calvin -k -H "Content-Type: application/json" -d "{\"Attributes\":{\"WebServer.1.HostHeaderCheck\":\"Disabled\"}}" -i
HTTP/1.1 200 OK
Date: Fri, 24 Jan 2025 20:08:09 GMT
Server: Apache
OData-Version: 4.0
Cache-Control: no-cache
X-Frame-Options: DENY
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
Content-Length: 506
Vary: Accept-Encoding
Content-Type: application/json;odata.metadata=minimal;charset=utf-8

{"@Message.ExtendedInfo":[{"Message":"The request completed successfully.","MessageArgs":[],"MessageArgs@odata.count":0,"MessageId":"Base.1.12.Success","RelatedProperties":[],"RelatedProperties@odata.count":0,"Resolution":"None","Severity":"OK"},{"Message":"The operation successfully completed.","MessageArgs":[],"MessageArgs@odata.count":0,"MessageId":"IDRAC.2.9.SYS413","RelatedProperties":[],"RelatedProperties@odata.count":0,"Resolution":"No response action is required.","Severity":"Informational"}]}
```

Thanks
Tex

**Comment by alexdatsko** [comment]
Thanks @texroemer !  I don't do a lot of API stuff from windows, I mostly use linux, but I've used it before in a pinch since it contains Curl etc.  However it looks like Powershell is the problem here, I should have known..

I can copy paste your exact curl command, substituting my IP:port and creds, and it works perfectly in cmd.exe.

However, when I copy the EXACT same command and paste it into the powershell interpreter, and change curl to be curl.exe (as curl is an alias for IWR in powershell), it still tells me the Json data is formatted incorrectly.

When in powershell I wrap that command in cmd.exe /c 'COMMAND' , it instead executes perfectly.

I think whats happening is, powershell is interpreting the data being sent as a powershell string, and either trying to execute { } as a scriptblock and parsing it from the data sent, etc.  This would make sense.  If it were non-tls and I could pcap I bet I would see some of the curly brackets missing or something similar..

It's frustrating when the tools don't do what we'd expect. Thanks again for your help!!!
