### ISSUE TITLE
Dell firmware update using redfish API - for 13G and 14G servers 

### ISSUE THREAD

**Issue by aviv12825** [dell/iDRAC-Redfish-Scripting#82]
Hi, 

I'm trying to find a way to update the servers components firmwares to latest firmware using the redfish api - maybe as a repo with or without catalog.xml file for 13G & 14G servers ?

Maybe somthing like this: 
https://www.dell.com/support/article/us/en/19/sln309728/dell-poweredge-how-to-update-the-firmware-via-https-connection-to-idrac?lang=en

Thanks 
Aviv

**Comment by texroemer** [comment]
Hi @aviv12825 

For Redfish using a Repository for updates, use OEM script "InstallFromRepositoryREDFISH.py". Example below is executing the script pointing to the Dell downloads HTTPS site which you can also use. Script will check the Dell downloads site and for any device which detects a firmware difference,it will update.


C:\Python27>InstallFromRepositoryREDFISH.py -ip 100.65.242.195 -u root -p calvin -i y --ipaddress 143.166.147.76 --sharetype HTTPS --applyupdate True --rebootneeded True

- WARNING, arguments and values for InstallFromRepository method

ShareType: HTTPS
RebootNeeded: True
ApplyUpdate: True
IPAddress: 143.166.147.76

- PASS: POST command passed for method "InstallFromRepository", status code 202 returned
- PASS, repository job ID JID_736759140333 successfully created
- WARNING, job ID JID_736759140333 not marked completed, current job information:

* Name: Repository Update
* Job Status: New
* Current job execution time: 0:00:00


- WARNING, repository package successfully downloaded. If version changed detected for any device, update job ID will get created and execute for that device

- WARNING, job ID JID_736759140333 not marked completed, current job information:

* Name: Repository Update
* Job Status: Package successfully downloaded.
* Current job execution time: 0:00:22

- WARNING, job ID JID_736759140333 not marked completed, current job information:

* Name: Repository Update
* Job Status: Package successfully downloaded.
* Current job execution time: 0:00:37

- WARNING, job ID JID_736759140333 not marked completed, current job information:

* Name: Repository Update
* Job Status: Package successfully downloaded.
* Current job execution time: 0:00:52

- WARNING, job ID JID_736759140333 not marked completed, current job information:

* Name: Repository Update
* Job Status: Package successfully downloaded.
* Current job execution time: 0:01:08

- WARNING, job ID JID_736759140333 not marked completed, current job information:

* Name: Repository Update
* Job Status: Package successfully downloaded.
* Current job execution time: 0:01:23

- WARNING, job ID JID_736759140333 not marked completed, current job information:

* Name: Repository Update
* Job Status: Package successfully downloaded.
* Current job execution time: 0:01:39

- WARNING, job ID JID_736759140333 not marked completed, current job information:

* Name: Repository Update
* Job Status: Package successfully downloaded.
* Current job execution time: 0:01:54

- WARNING, job ID JID_736759140333 not marked completed, current job information:

* Name: Repository Update
* Job Status: Package successfully downloaded.
* Current job execution time: 0:02:10

- PASS, job ID JID_736759140333 successfully marked completed

- Final detailed job results -

@odata.type: #DellJob.v1_0_2.DellJob
JobState: Completed
Description: Job Instance
TargetSettingsURI: None
@odata.id: /redfish/v1/Managers/iDRAC.Embedded.1/Jobs/JID_736759140333
@odata.context: /redfish/v1/$metadata#DellJob.DellJob
MessageArgs: [u'NA']
PercentComplete: 100
CompletionTime: 2019-11-13T14:24:31
MessageArgs@odata.count: 1
StartTime: TIME_NOW
MessageId: RED001
Message: Job completed successfully.
EndTime: None
Id: JID_736759140333
JobType: RepositoryUpdate
Name: Repository Update



- WARNING, repository update job marked completed. Script will now check to see if any update job(s) were created due to different firmware version change detected

- PASS, job ID JID_736759279421 successfully marked completed

- Final detailed job results -

@odata.type: #DellJob.v1_0_2.DellJob
JobState: Completed
Description: Job Instance
TargetSettingsURI: None
@odata.id: /redfish/v1/Managers/iDRAC.Embedded.1/Jobs/JID_736759279421
@odata.context: /redfish/v1/$metadata#DellJob.DellJob
MessageArgs: []
PercentComplete: 100
CompletionTime: 2019-11-13T14:24:30
MessageArgs@odata.count: 0
StartTime: TIME_NOW
MessageId: PR19
Message: The specified job has completed successfully.
EndTime: TIME_NA
Id: JID_736759279421
JobType: FirmwareUpdate
Name: Firmware Update: BIOS



- PASS, job ID JID_736759541406 successfully marked completed

- Final detailed job results -

@odata.type: #DellJob.v1_0_2.DellJob
JobState: Completed
Description: Job Instance
TargetSettingsURI: None
@odata.id: /redfish/v1/Managers/iDRAC.Embedded.1/Jobs/JID_736759541406
@odata.context: /redfish/v1/$metadata#DellJob.DellJob
MessageArgs: []
PercentComplete: 100
CompletionTime: 2019-11-13T14:24:30
MessageArgs@odata.count: 0
StartTime: TIME_NOW
MessageId: PR19
Message: Job completed successfully.
EndTime: TIME_NA
Id: JID_736759541406
JobType: FirmwareUpdate
Name: Firmware Update: Serial ATA



- PASS, job ID JID_736759753446 successfully marked completed

- Final detailed job results -

@odata.type: #DellJob.v1_0_2.DellJob
JobState: Completed
Description: Job Instance
TargetSettingsURI: None
@odata.id: /redfish/v1/Managers/iDRAC.Embedded.1/Jobs/JID_736759753446
@odata.context: /redfish/v1/$metadata#DellJob.DellJob
MessageArgs: []
PercentComplete: 100
CompletionTime: 2019-11-13T14:24:30
MessageArgs@odata.count: 0
StartTime: TIME_NOW
MessageId: PR19
Message: Job completed successfully.
EndTime: TIME_NA
Id: JID_736759753446
JobType: FirmwareUpdate
Name: Firmware Update: Firmware



- PASS, job ID JID_736759915255 successfully marked completed

- Final detailed job results -

@odata.type: #DellJob.v1_0_2.DellJob
JobState: Completed
Description: Job Instance
TargetSettingsURI: None
@odata.id: /redfish/v1/Managers/iDRAC.Embedded.1/Jobs/JID_736759915255
@odata.context: /redfish/v1/$metadata#DellJob.DellJob
MessageArgs: []
PercentComplete: 100
CompletionTime: 2019-11-13T14:13:25
MessageArgs@odata.count: 0
StartTime: TIME_NOW
MessageId: RED001
Message: Job completed successfully.
EndTime: None
Id: JID_736759915255
JobType: FirmwareUpdate
Name: Firmware Update: Diagnostics



- PASS, job ID JID_736760128111 successfully marked completed

- Final detailed job results -

@odata.type: #DellJob.v1_0_2.DellJob
JobState: Completed
Description: Job Instance
TargetSettingsURI: None
@odata.id: /redfish/v1/Managers/iDRAC.Embedded.1/Jobs/JID_736760128111
@odata.context: /redfish/v1/$metadata#DellJob.DellJob
MessageArgs: []
PercentComplete: 100
CompletionTime: 2019-11-13T14:15:24
MessageArgs@odata.count: 0
StartTime: TIME_NOW
MessageId: RED001
Message: Job completed successfully.
EndTime: None
Id: JID_736760128111
JobType: FirmwareUpdate
Name: Firmware Update: Drivers for OS Deployment


- WARNING, job ID JID_736766716864 not marked completed, current job information:

* Name: update:DCIM:INSTALLED#iDRAC.Embedded.1-1#IDRACinfo
* Job Status: Downloading the iDRAC-with-Lifecycle-Controller_Firmware_HFMCV_WN64_3.36.36.36_A00.EXE update package.
* Current job execution time: 0:00:00

- WARNING, job ID JID_736766716864 not marked completed, current job information:

* Name: update:DCIM:INSTALLED#iDRAC.Embedded.1-1#IDRACinfo
* Job Status: Downloading the iDRAC-with-Lifecycle-Controller_Firmware_HFMCV_WN64_3.36.36.36_A00.EXE update package.
* Current job execution time: 0:00:16

- WARNING, job ID JID_736766716864 not marked completed, current job information:

* Name: update:DCIM:INSTALLED#iDRAC.Embedded.1-1#IDRACinfo
* Job Status: Downloading the iDRAC-with-Lifecycle-Controller_Firmware_HFMCV_WN64_3.36.36.36_A00.EXE update package.
* Current job execution time: 0:00:31

- WARNING, job ID JID_736766716864 not marked completed, current job information:

* Name: update:DCIM:INSTALLED#iDRAC.Embedded.1-1#IDRACinfo
* Job Status: Downloading the iDRAC-with-Lifecycle-Controller_Firmware_HFMCV_WN64_3.36.36.36_A00.EXE update package.
* Current job execution time: 0:00:47




- PASS, job ID JID_736766716864 successfully marked completed

- Final detailed job results -

@odata.type: #DellJob.v1_0_2.DellJob
JobState: Completed
Description: Job Instance
TargetSettingsURI: None
@odata.id: /redfish/v1/Managers/iDRAC.Embedded.1/Jobs/JID_736766716864
@odata.context: /redfish/v1/$metadata#DellJob.DellJob
MessageArgs: []
PercentComplete: 100
CompletionTime: 2019-11-13T14:27:24
MessageArgs@odata.count: 0
StartTime: TIME_NOW
MessageId: RED001
Message: Job completed successfully.
EndTime: None
Id: JID_736766716864
JobType: FirmwareUpdate
Name: Firmware Update: iDRAC with Lifecycle Controller



C:\Python27>
