### ISSUE TITLE
Redfish API to retrive PSU is getting failed due to KeyError: PowerSupplies

### ISSUE THREAD

**Issue by gsakkar** [dell/iDRAC-Redfish-Scripting#93]
LC Version of the IDRAC is : 3.34.34.34
I am getting the PowerSupplies Key error  used against with 3.34 version lower than 4.00
 python GetSystemHWinv-new.py -ip 192.168.102.39 -u root -p calvin -ps y

---- Power Supply Information ----

Traceback (most recent call last):
  File "GetSystemHWinv-new.py", line 570, in <module>
    get_ps_information()
  File "GetSystemHWinv-new.py", line 271, in get_ps_information
    for iii in data_get['PowerSupplies']:
KeyError: 'PowerSupplies'

I would like to understand how are we maintain the backward compatibility with lower version incase if any API changes in new version - how are we handling version independent of Redfish changes.

**Comment by texroemer** [comment]
Hi @gsakkar 

For Dell Redfish GitHub content, I’m always updating content to work with latest version of iDRAC that is posted on Dell support site for download. When a new iDRAC version is released, this version will contain new Redfish content (DMTF and OEM) which is why it's recommended to use latest iDRAC version available.

For backwards compatibility, I try to handle these scenarios in the scripts but this was a miss in script GetSystemHWInventoryREDFISH.py. I updated the script and added exceptions in the code for backwards compatibility, new script has been uploaded.

Thanks
